### ISSUE TITLE
How to compile decrypter?

### ISSUE THREAD

**Issue by kasgeg** [x-hgg-x/video_decrypter#1]
I tried doing cmake on /src/ folder, and it does give me a Makefile, but it gives me some errors, and it doesn't work if I use ignore errors option.
```
lib/expat/lib/xmlparse.c:1450:12: error: 'XML_ERROR_INVALID_ARGUMENT' undeclared (first use in this function)
```

**Comment by FloridaStream** [comment]
@kasgeg @x-hgg-x 

Same here, cant compile on Visual Studio 2017, need some libs and fix for compile on windows.

**Comment by x-hgg-x** [comment]
You need to compile with MinGW-w64 on Windows.

**Comment by FloridaStream** [comment]
@x-hgg-x ok, i will try now and back with result.
