### ISSUE TITLE
Known issues

### ISSUE THREAD

**Issue by x-hgg-x** [x-hgg-x/video_decrypter#10]
For some videos, the program crashes when writing decrypted tracks, because the size of the encrypted and decrypted samples are not the same.

**Comment by x-hgg-x** [comment]
The problem is in main.cpp in FragmentedSampleReader::ReadSample() after this comment :
 // Write initialisation & data into decrypted file.

I'm open to suggestions or pull requests to write decrypted tracks with libbento4.

**Comment by FloridaStream** [comment]
You close the issue, u can fix it?

**Comment by x-hgg-x** [comment]
It is related to frame decode, it will take some time.

**Comment by drt420** [comment]
is it doable?

**Comment by drt420** [comment]
i was wondering why dont we save raw frames which was also done by wvdownloader in past

**Comment by FloridaStream** [comment]
Hi @x-hgg-x 
Just out of curiosity, why did not you use the latest version of inpustream.adaptive as the basis for FragmentedSampleReader::ReadSample()?

Would it be possible for you to upgrade to use the inputstream.adaptive (2.2.24) version as source?

I think it would be easier for you than for me to do that.

If you want to speak in private, a direct link to my skype is below.
https://join.skype.com/invite/Tq6RyA9JhM1d

See you bro.
