### ISSUE TITLE
Unable to select stream! error

### ISSUE THREAD

**Issue by tsukasachandesu** [x-hgg-x/video_decrypter#11]
Thank you for fixing no m﻿oov in stream! e﻿rro﻿r but I got errors when I try decrypting mpd except some mpd. 
For example,
https://bitmovin.com/demos/drm
https://bitmovin-a.akamaihd.net/content/art-of-motion_drm/mpds/11331.mpd
https://widevine-proxy.appspot.com/proxy

CDMMessage: 3 arrived!
OpenStream(1)
Selecting ...
Unable to select stream!

Also, I found a solution to AMZN's license issue but I got Unable to select stream! error.
Does anyone solve Unable to select stream! error?

**Comment by drt420** [comment]
You are not selecting correct MPD file

**Comment by tsukasachandesu** [comment]
widevine_decrypter concatenated_video 1 license_folder decrypted_folder
Do I need edit mpd?

**Comment by drt420** [comment]
i said u need correct mpd file with correct info :)

**Comment by tsukasachandesu** [comment]
Sorry...
I do not know how to correct mpd file.

**Comment by drt420** [comment]
how are u saving license key and how are you downloading mp4 file?

**Comment by tsukasachandesu** [comment]
license_key.txt is https://widevine-proxy.appspot.com/proxy||A{SSM}|.
i concatnated init.mp4 with m4f.

**Comment by drt420** [comment]
thats where issue is in saving mp4 file

**Comment by drt420** [comment]
i m saying the way u r saving mp4 file is not correct as u r modify original file

**Comment by tsukasachandesu** [comment]
Someone who can decrypt bitmovin send me concatenated video(encrypted).
I tried it but I got same error.

**Comment by drt420** [comment]
@FloridaStream Share ur skype or irc as i dont want to discuss publicly for some reasons

**Comment by tsukasachandesu** [comment]
Please contact me.
https://join.slack.com/t/widdec/shared_invite/enQtMzk4NjA2OTEzODkwLWZlMjdjZTYzMDlmNTBiZTVkMzBiZjhjMjRjMjQwMGQxZTk0MDE2ZDQxYjAwOTNiNzE4YWFjNDI3MmI4NDVmY2Y

**Comment by FloridaStream** [comment]
@drt420 Skype: **rannyere_santos**
 I will edit it after you contact me :)

**Comment by drt420** [comment]
@FloridaStream i m not able to find u pls add me on skype @ adi10689

**Comment by x-hgg-x** [comment]
@FloridaStream 

The script https://github.com/x-hgg-x/video_decrypter/blob/master/python_scripts/1.%20script_liens.py does not change the manifest file, it only searches and list fragment urls from manifest.
