### ISSUE TITLE
bitmovin drm demo

### ISSUE THREAD

**Issue by sumanex** [x-hgg-x/video_decrypter#13]
Hello, i just compiled the widevine_decrypter with cmake and make.I am in win 7.
However I am always getting the error  Invalid licence key.
I have combined the init.mp4 and m4s segm,ents and combined them to the source.mp4 file.
I have the manifest mpd file( the decrypter says successfully parsed mpd ) stream 2 , no error in the info paths. 

the licence is from the  bitmovin i tried all combinations the R SSM, A SSSM and the B SSM. no luck
""www......."&User-Agent=Mozilla%2F5.0|R{SSM}|

then it enters encryption section and shows the invalid licence key eror, Can you give me some clues.
thanks

**Comment by FloridaStream** [comment]
Maybe problem in manifest.mpd?

For bitmovin i use `https://widevine-proxy.appspot.com/proxy||A{SSM}|` but i cant pass the `mpd`, i no have idea how to fix `mpd`. 

_**Waiting for help too**. Im using last version,i have updated the decrypter to last inputstream version and some other files._

**Comment by sumanex** [comment]
yes I want to try I have downloaded the manifest and the licence from azure website.
But how do I get all the encrypted video fragments of the manifest i.e. the fragments ?
plz suggest.

**Comment by sumanex** [comment]
thanks

**Comment by Ayrler** [comment]
How do you actually get license file ?
```File : mpd-time-csf.mp4
Info path : .\info
Decrypted path : .\decrypted
Initialisation...
Successfully parsed .mpd file. #Streams: 3
Entering encryption section
Invalid license_key```
Using the link provided by @FloridaStream as a test stream, I couldn't download the license key file nor actually find it even if I see that some posts are made with the KID.

**Comment by Ayrler** [comment]
I couldn't get it to work with some other azure based widevine players.
When using the license url I have this response:
```
<Error><Message>Failed authorization policy evaluation.</Message><Code>Unauthorized</Code></Error>```
Is there any solution to that ?

**Comment by FloridaStream** [comment]
@Ayrler you need to use the correct url, with the correct parameters. see previous posts.

One tip, there is no way anyone can help you without you helping yourself, put the codes you are using so people know how to identify the problem in them. 😎

**Comment by Ayrler** [comment]
@FloridaStream Got it working, thanks.
