### ISSUE TITLE
mpd format issue

### ISSUE THREAD

**Issue by tsukasachandesu** [x-hgg-x/video_decrypter#3]
Here is https:// bitmovin-a.akamaihd.net/content/art-of-motion_drm/mpds/11331.mpd in 
https:// bitmovin.com/demos/drm. 
I tried 1. script_liens.py but 2. script_download.py didn't work.

../video/$RepresentationID$/cenc_dash/init.mp4
../audio/$RepresentationID$/cenc_dash/init.mp4

Can I decrypt this video, if I manually download m4f?

**Comment by x-hgg-x** [comment]
The python scripts are not universal, you need to adapt it for each website to work.
See wiki for usage steps.
