### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by drt420** [x-hgg-x/video_decrypter#6]
Hello
I am directly passing arguments through command line and it is not working. Can u pls help me in getting it worked. My info folder has both license_key.txt and maifest.mpd

```
D:\New folder (2)>widevine_decrypter
Syntax : program.exe {encrypted_file} {info_path} {decrypted_path}
D:\New folder (2)>widevine_decrypter video_e.mp4 info/ decrypted/

D:\New folder (2)>
```

**Comment by x-hgg-x** [comment]
Can you show me your manifest and license key file ?

**Comment by drt420** [comment]
yes pls find as below and also share ur skype or irc so that i can have some private talk lol which i cannot do publically for some security reasons.

License Key:  https://pastebin.com/RrX44mUi
MPD File : https://files.fm/u/h5uk8z7x

**Comment by x-hgg-x** [comment]
Join me on Slack :
https://join.slack.com/t/videodecrypter/shared_invite/enQtMzkzOTM2NDc3ODI0LWZhNzc1NTAzOGM1ZWNhOGQyMmI4ZjY0MWI1M2VhYzg0Y2Y5ZmM0NWNlNTgyMWUxZTljNjIwYjZiOTkyNDE2NDM

**Comment by FloridaStream** [comment]
I have a similar problem, I am passing the arguments, but I do not get any error log or debug to help me.
Nothing happens.
