### ISSUE TITLE
no m﻿oov in stream! e﻿rro﻿r

### ISSUE THREAD

**Issue by tsukasachandesu** [x-hgg-x/video_decrypter#8]
Hello,
I could decrypt a mpd like your sample. Thank you!
I tried decrypt mpd which have init.mp4 and m4f.
I combinated init.mp4 with m4f.
I suceeded in getting license but got no m﻿oov in﻿ ﻿stream! e﻿rro﻿r﻿. 
If you cannot do publically for some security reasons, pls share ur skype or irc.

**Comment by daw134** [comment]
can you explain what you did exactly?

**Comment by tsukasachandesu** [comment]
I can decrypt azure's mpd but failed decrypting other mpds.    
for example, 
dash: 'https://bitmovin-a.akamaihd.net/content/art-of-motion_drm/mpds/11331.mpd'
license: 'https://widevine-proxy.appspot.com/proxy'
I tried concatenating the init.mp4 with all of segments but i got Unable to select stream!.
I think I need to add modification to the mpd but I do not how to do.

**Comment by daw134** [comment]
Hey, can we work together on this? I’m struggling and I think you’re getting somewhere and I think we may be able to help each other out?

Sent from my iPhone

On 10 Jul 2018, at 20:41, tsukasachandesu <notifications@github.com<mailto:notifications@github.com>> wrote:


I can decrypt azure's mpd but failed decrypting other mpds.
for example,
dash: 'https://bitmovin-a.akamaihd.net/content/art-of-motion_drm/mpds/11331.mpd<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbitmovin-a.akamaihd.net%2Fcontent%2Fart-of-motion_drm%2Fmpds%2F11331.mpd&data=02%7C01%7C%7Cb2394cad23ca48cacdff08d5e69d3053%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636668485146590492&sdata=Gpyg25BfwkMEofKg%2BK7%2Fct3Jwr2FEf7UbUJa3%2FDCOVM%3D&reserved=0>'
license: 'https://widevine-proxy.appspot.com/proxy<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwidevine-proxy.appspot.com%2Fproxy&data=02%7C01%7C%7Cb2394cad23ca48cacdff08d5e69d3053%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636668485146590492&sdata=Yek%2Bwp4TYviWnDB6BOS3tGR9%2B%2FyEa8fFwuHViT95cPE%3D&reserved=0>'
I tried concatenating the init.mp4 with all of segments but i got Unable to select stream!.
I think I need to add modification to the mpd but I do not how to do.

**Comment by tsukasachandesu** [comment]
Join me on Slack :
https://join.slack.com/t/wvdhq/shared_invite/enQtMzk2MzM1NDUwNzA2LTc2MTMxMjE3NTI4ODBmMzFmZGEwYWY0OGM0NjlkMjU5ZDEwYmU3YTc5MjY2ZGEzYjNjYTFhMGM5OGQ3MGQyNzg

**Comment by FloridaStream** [comment]
@tsukasachandesu @daw134 
Yous could help me, I'm trying to test with bitmovin, but I'm not getting it, I always get the error below:
License update not successful (no keys)
Initialize failed (SingleSampleDecrypter)

Can you tell me what they are using in license_key.txt?
I think I'm riding the wrong way.

If you can not talk here, just let me know that we speak by other means.

From what I've seen, the inputstream.adaptive addon can handle the .response without any problems. Maybe because additional parameters are passed, I'm not sure.

**Comment by x-hgg-x** [comment]
See with @drt420 from Issue #6.
